version: "1.0"

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file: ./.env
    ports:
      - $ME_CONFIG_MONGODB_PORT:$ME_CONFIG_MONGODB_PORT
    volumes:
      - ./mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=$MONGO_INITDB_DATABASE
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    env_file: ./.env
    restart: always
#    no: 재시작 하지 않음.
#    always: exit code와 상관없이 항상 재시작.
#    on-failure: exit code가 0일 아닐때(비정상 종료인 경우)만 재시작
#    unless-stopped: 컨테이너 상태를 수동으로 stop 하기전까지 재시작.
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=$ME_CONFIG_MONGODB_SERVER
      - ME_CONFIG_MONGODB_PORT=$ME_CONFIG_MONGODB_PORT
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_INITDB_ROOT_USERNAME # mongodb 컨테이너의 root 계정
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_INITDB_ROOT_PASSWORD # mongodb 컨테이너의 root 비밀번호
      - ME_CONFIG_BASICAUTH_USERNAME=$ME_CONFIG_BASICAUTH_USERNAME # express 계정
      - ME_CONFIG_BASICAUTH_PASSWORD=$ME_CONFIG_BASICAUTH_PASSWORD  # express 비밀번호
      # - ME_CONFIG_MONGODB_ENABLE_ADMIN=true # 모든 DB에 관리자권한으로 연결 (기본값 true)

  mysqldb:
    image: mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql

  app:
    depends_on:
      - mongodb
      - mysqldb
    build: . # 동일 디렉토리에 위치한 Dockerfile을 사용하여 web 서비스 이미지 빌드
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.r2dbc.url" : "r2dbc:mysql://mysqldb:3306/test",
          "spring.r2dbc.username" : "root",
          "spring.r2dbc.password" : "1234",
          "spring.data.mongodb.uri" : "mongodb://mongodb:27017/test",
          "spring.data.mongodb.username" : "root",
          "spring.data.mongodb.password" : "1234"
        }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  data: {}
  db:

networks:
  default:
    name: mongodb_network